# index:
#     path: /
#     controller: App\Controller\DefaultController::index

getPostsFromCategory:
    path: /getPostsFromCategory/{category}
    controller: App\Controller\DataController::getPostsFromCategory
    methods:  [POST]